---
service_type: "ClusterIP"
backrest_port: "2022"
cleanup: "false"
crunchy_debug: "false"

kubernetes_deployment_name: "pgo"
kubernetes_base_path: "{{ local_base_config_path|default('~/') }}/.{{ kubernetes_deployment_name }}-config"

storage1_supplemental_groups: ''
storage1_fs_group: ''
storage2_supplemental_groups: ''
storage2_fs_group: ''
storage3_supplemental_groups: ''
storage3_fs_group: ''
