---
backrest_port: "2022"
cleanup: "false"
common_name: "crunchydata"
crunchy_debug: "false"

kubernetes_deployment_name: "pgo"

storage1_supplemental_groups: ''
storage1_fs_group: ''
storage2_supplemental_groups: ''
storage2_fs_group: ''
storage3_supplemental_groups: ''
storage3_fs_group: ''
