---
- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: '{{ output_dir }}'
    state: directory
  tags: [install]

- name: Generate RSA Key
  command: openssl genrsa \
    -out "{{ output_dir }}/privkey.pem" 2048
  args:
    creates: "{{ output_dir }}/privkey.pem"
  tags: [install]

- name: Generate CSR
  command: openssl req \
    -new \
    -subj '/C=US/ST=SC/L=Charleston/O=CrunchyData/CN=pg-operator' \
    -key "{{ output_dir }}/privkey.pem" \
    -out "{{ output_dir }}/pg-operator.csr"
  args:
    creates: "{{ output_dir }}/pg-operator.csr"
  tags: [install]

- name: Generate Self-signed Certificate
  command: openssl req \
    -x509 \
    -days 1825 \
    -key "{{ output_dir }}/privkey.pem" \
    -in "{{ output_dir }}/pg-operator.csr" \
    -out "{{ output_dir }}/pg-operator.crt"
  args:
    creates: "{{ output_dir }}/pg-operator.crt"
  tags: [install]
