---
- fail:
    msg: "Only set one of kubernetes_context or openshift_host"
  when: openshift_host is defined and kubernetes_context is defined
  tags: always

- include_tasks: "{{ tasks }}"
  with_items:
    - openshift_auth.yml
    - openshift.yml
  loop_control:
    loop_var: tasks
  when: openshift_host is defined
  tags: always

- include_tasks: "{{ tasks }}"
  with_items:
    - kubernetes_auth.yml
    - kubernetes.yml
  loop_control:
    loop_var: tasks
  when: kubernetes_context is defined
  tags: always

- include_tasks: certs.yml
  tags: [install]

- include_tasks: ssh_keys.yml
  tags: [install]

- include_tasks: cleanup.yml
  tags: [deprovision, upgrade]

- include_tasks: deprecated.yml
  tags: always

- name: Use kubectl or oc
  set_fact:
    kubectl_or_oc: "{{ openshift_oc_bin if openshift_oc_bin is defined else 'kubectl' }}"
  tags: always

- name: Deploy PostgreSQL Operator (OpenShift)
  tags: [install, upgrade]
  block:
    - name: Create PGO CRDs
      shell: |
        {{ kubectl_or_oc }} create -f \
          {{ role_path }}/files/crd.yaml -n {{ kubernetes_namespace }}
      ignore_errors: yes
      no_log: true

    - name: Template Cluster RBAC
      template:
        src: cluster-rbac.yaml.j2
        dest: "{{ kubernetes_base_path }}/cluster-rbac.yaml"
        mode: '0600'

    - name: Create Cluster RBAC
      shell: |
        {{ kubectl_or_oc }} create -f \
          {{ kubernetes_base_path }}/cluster-rbac.yaml -n {{ kubernetes_namespace }}
    
    - name: Template PGO RBAC
      template:
        src: rbac.yaml.j2
        dest: "{{ kubernetes_base_path }}/rbac.yaml"
        mode: '0600'

    - name: Create PGO RBAC
      shell: |
        {{ kubectl_or_oc }} create -f \
          {{ kubernetes_base_path }}/rbac.yaml -n {{ kubernetes_namespace }}

    - name: Template PGO User
      template:
        src: pgouser.j2
        dest: "{{ kubernetes_base_path }}/pgouser"
        mode: '0600'

    - name: Template Local PGO User
      template:
        src: pgouser.local.j2
        dest: "~/.pgouser"
        mode: '0400'

    - name: Template PGO Configuration
      template:
        src: pgo.yaml.j2
        dest: "{{ kubernetes_base_path }}/pgo.yaml"
        mode: '0600'

    - name: Create PGO BackRest Repo ConfigMap
      shell: |
        {{ kubectl_or_oc }} create secret generic pgo-backrest-repo-config \
          --from-file=authorized_keys='{{ kubernetes_base_path }}/authorized_keys' \
          --from-file=id_rsa='{{ kubernetes_base_path }}/id_rsa' \
          --from-file=ssh_host_rsa_key='{{ kubernetes_base_path }}/ssh_host_rsa_key' \
          --from-file=ssh_host_ecdsa_key='{{ kubernetes_base_path }}/ssh_host_ecdsa_key' \
          --from-file=ssh_host_ed25519_key='{{ kubernetes_base_path }}/ssh_host_ed25519_key' \
          --from-file=sshd_config='{{ role_path }}/files/pgo-backrest-repo/sshd_config' \
          --from-file=config='{{ role_path }}/files/pgo-backrest-repo/config' \
          -n {{ kubernetes_namespace }}
      ignore_errors: yes
      no_log: true

    - name: Create PGO API Secret
      shell: |
        {{ kubectl_or_oc }} create secret generic pgo-auth-secret \
          --from-file=server.crt='{{ kubernetes_base_path }}/pg-operator.crt' \
          --from-file=server.key='{{ kubernetes_base_path }}/privkey.pem' \
          --from-file=pgouser='{{ kubernetes_base_path }}/pgouser' \
          --from-file=pgorole='{{ role_path }}/files/pgorole' \
          -n {{ kubernetes_namespace }}
      ignore_errors: yes
      no_log: true

    - name: Create PGO ConfigMap
      shell: |
        {{ kubectl_or_oc }} create configmap pgo-config \
          --from-file=pgo.yaml='{{ kubernetes_base_path }}/pgo.yaml' \
          --from-file={{ role_path }}/files/pgo-configs \
          --from-file={{ role_path }}/files/pgo-configs/cluster/1 \
          -n {{ kubernetes_namespace }}

    - name: Create PGO Service
      shell: |
        {{ kubectl_or_oc }} create --filename='{{ role_path }}/files/service.json' \
          -n {{ kubernetes_namespace }}

    - name: Template PGO Deployment
      template:
        src: deployment.json.j2
        dest: "{{ kubernetes_base_path }}/deployment.json"
        mode: '0600'

    - name: Deploy PGO
      shell: |
        {{ kubectl_or_oc }} create --filename={{ kubernetes_base_path }}/deployment.json \
          -n {{ kubernetes_namespace }}
