---
- name: Check if inventory file variables are defined for Prometheus
  fail: msg="Please specify the value of {{item}} in your inventory file"
  tags: always
  when: "item is undefined or item == '' and prometheus_install == 'true'"
  with_items:
  - metrics_namespace
  - prometheus_service_name
  - prometheus_port
  - prometheus_storage_access_mode
  - prometheus_storage_class_name
  - prometheus_volume_size

- name: Check if inventory file variables are defined for Grafana
  fail: msg="Please specify the value of {{item}} in your inventory file"
  tags: always
  when: "item is undefined or item == '' and grafana_install == 'true'"
  with_items:
  - metrics_namespace
  - grafana_install
  - grafana_admin_username
  - grafana_admin_password
  - grafana_port
  - grafana_service_name
  - grafana_default_dashboards
  - grafana_storage_access_mode
  - grafana_storage_class_name
  - grafana_volume_size
